//! Generated package manifest and RustaSea application manifest.
//!
//! The `Cargo.toml` template is the one file whose *dependency features* differ
//! per variant, so each kit gets its own manifest string. Everything else in
//! the tree is byte-identical across variants.

use crate::variant::StarterKitVariant;

use super::TemplateFile;

/// Manifest templates for `variant`.
pub fn entries(variant: StarterKitVariant) -> Vec<TemplateFile> {
    vec![
        ("Cargo.toml", cargo_toml(variant)),
        ("rustasea.toml", RUSTASEA_TOML),
    ]
}

/// Select the variant-specific `Cargo.toml` template.
fn cargo_toml(variant: StarterKitVariant) -> &'static str {
    match variant {
        StarterKitVariant::Blade => BLADE_CARGO,
        StarterKitVariant::React => REACT_CARGO,
        StarterKitVariant::Vue => VUE_CARGO,
        StarterKitVariant::Livewire => LIVEWIRE_CARGO,
    }
}

const BLADE_CARGO: &str = r##"[package]
name = "@@app_name@@"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
description = "@@app_pascal@@ — a RustaSea blade starter kit"

[lib]
name = "@@app_snake@@"
path = "lib.rs"

[[bin]]
name = "@@app_name@@"
path = "main.rs"

[dependencies]
rustasea = { version = "0.1", features = ["view"] }
rustasea-view = "0.1"
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
default = []

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
"##;

const REACT_CARGO: &str = r##"[package]
name = "@@app_name@@"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
description = "@@app_pascal@@ — a RustaSea react (Dioxus + Inertia) starter kit"

[lib]
name = "@@app_snake@@"
path = "lib.rs"

[[bin]]
name = "@@app_name@@"
path = "main.rs"

[dependencies]
rustasea = { version = "0.1", features = ["inertia", "wasm-dioxus"] }
rustasea-inertia = "0.1"
rustasea-inertia-adapters = { version = "0.1", features = ["react"] }
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
default = []

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
"##;

const VUE_CARGO: &str = r##"[package]
name = "@@app_name@@"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
description = "@@app_pascal@@ — a RustaSea vue (Leptos + Inertia) starter kit"

[lib]
name = "@@app_snake@@"
path = "lib.rs"

[[bin]]
name = "@@app_name@@"
path = "main.rs"

[dependencies]
rustasea = { version = "0.1", features = ["inertia", "wasm-leptos"] }
rustasea-inertia = "0.1"
rustasea-inertia-adapters = { version = "0.1", features = ["vue"] }
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
default = []

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
"##;

const LIVEWIRE_CARGO: &str = r##"[package]
name = "@@app_name@@"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
description = "@@app_pascal@@ — a RustaSea livewire (askama + HTMX) starter kit"

[lib]
name = "@@app_snake@@"
path = "lib.rs"

[[bin]]
name = "@@app_name@@"
path = "main.rs"

[dependencies]
rustasea = { version = "0.1", features = ["view", "broadcast"] }
rustasea-view = "0.1"
rustasea-livewire = "0.1"
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
default = []

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
"##;

const RUSTASEA_TOML: &str = r##"# Application manifest consumed by RustaSea tooling.
# Generated by `cargo rustasea new`; safe to edit.
[app]
name = "@@app_name@@"
variant = "@@variant@@"
msrv = "1.88"
"##;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cargo_manifest_carries_variant_features() {
        let blade = cargo_toml(StarterKitVariant::Blade);
        assert!(blade.contains("features = [\"view\"]"));
        let react = cargo_toml(StarterKitVariant::React);
        assert!(react.contains("wasm-dioxus"));
        assert!(react.contains("features = [\"react\"]"));
        let vue = cargo_toml(StarterKitVariant::Vue);
        assert!(vue.contains("wasm-leptos"));
        assert!(vue.contains("features = [\"vue\"]"));
        let livewire = cargo_toml(StarterKitVariant::Livewire);
        assert!(livewire.contains("features = [\"view\", \"broadcast\"]"));
    }

    #[test]
    fn every_manifest_has_the_shared_tail() {
        for variant in StarterKitVariant::ALL {
            let manifest = cargo_toml(variant);
            assert_eq!(manifest.matches("serde_json = \"1\"").count(), 1);
            assert!(manifest.contains("[dev-dependencies]"));
        }
    }
}
