//! CLI command registry — console commands registered at application boot.
//!
//! The runnable app owns no commands of its own yet; registering the
//! framework's built-in surface keeps `Artisan::call` / `cargo artisan`
//! dispatch working for the same process, mirroring Laravel's console kernel
//! registration. Commands generated by `cargo artisan make:command` are
//! appended here.

/// Register the framework's built-in console commands into the process-wide
/// registry.
///
/// Idempotent per command name: later registrations replace earlier ones.
pub fn register_default() {
    rustasea::cli::load_default_commands();
}
