//! Provider registry — service providers wired into the app boot DAG.
//!
//! `bootstrap/app.rs::configure` consumes this registry, so providers
//! generated by `cargo artisan make:provider` are appended here.

use rustasea::{Application, ServiceProvider};

/// Application service provider.
///
/// Owns app-level container bindings. Framework services (config, ORM, auth,
/// queue, …) register through their own providers as they land; this one
/// stays a no-op scaffold until the app has its own bindings.
pub struct AppServiceProvider;

impl ServiceProvider for AppServiceProvider {
    /// Stable provider name used for dependency resolution.
    fn name(&self) -> &'static str {
        "AppServiceProvider"
    }

    /// Register bindings into the container.
    fn register(&self, _app: &mut Application) {}

    /// Boot after all providers have registered.
    fn boot(&self, _app: &Application) {}
}

/// Return the providers registered for the application boot DAG.
///
/// Order is the tie-breaker for providers without `dependencies()`; the
/// foundation [`Application::boot`] topologically sorts them regardless.
pub fn providers() -> Vec<Box<dyn ServiceProvider>> {
    vec![Box::new(AppServiceProvider)]
}
