[package]
name = "rustavel"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rustavel-foundation = { path = "../rustavel-foundation" }
rustavel-config = { path = "../rustavel-config" }
rustavel-router = { path = "../rustavel-router" }
rustavel-http = { path = "../rustavel-http" }
rustavel-macros = { path = "../rustavel-macros" }
rustavel-orm = { path = "../rustavel-orm" }
