[package]
name = "rustavel-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Procedural macros for Rustavel — #[route], #[middleware], #[authorize], #[validate]"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
