//! Built-in console commands — `list` and the `make:*` generator family.
//!
//! All built-ins dispatch through the same [`Command`] trait the generators
//! emit, so `Artisan::call("migrate", vec![]).await` runs the identical code
//! path as `cargo rustavel migrate` (FR-502, FR-505).

use async_trait::async_trait;

use crate::artisan::{Command, Io};
use crate::error::CliResult;
use crate::generator::Generated;
use crate::generators::{self, Kind, MakeOptions};
use crate::output;

/// `list` — enumerate registered commands (FR-500).
pub struct List;

#[async_trait]
impl Command for List {
    /// Command signature.
    fn signature(&self) -> &'static str {
        "list"
    }

    /// Usage line rendered by `list`.
    fn usage(&self) -> Option<&'static str> {
        Some("list [--json] [--all]")
    }

    /// One-line help rendered by `list`.
    fn help(&self) -> Option<&'static str> {
        Some("List available commands")
    }

    /// Execute: emit a table (default) or JSON (--json), filtering hidden.
    async fn run(&self, args: Vec<String>, io: &mut Io) -> CliResult<()> {
        let json = args.iter().any(|a| a == "--json");
        let all = args.iter().any(|a| a == "--all" || a == "-a");
        let metas = crate::Artisan::list(all);

        if json {
            io.line(serde_json::to_string(&metas)?);
            return Ok(());
        }

        let mut rows = vec![vec!["Command".into(), "Description".into()]];
        for meta in metas {
            let description = if meta.help.is_empty() {
                meta.usage.clone()
            } else {
                meta.help.clone()
            };
            rows.push(vec![meta.name.clone(), description]);
        }
        io.line(output::table(rows).trim_end());
        Ok(())
    }
}

/// Shared `make:*` run logic.
///
/// The first positional arg is the PascalCase scaffold name. Flags are read
/// position-independently: `--force`, `--resource`, `-m`/`--migration`.
async fn run_make(kind: Kind, args: Vec<String>, io: &mut Io) -> CliResult<()> {
    let name = args
        .first()
        .filter(|n| !n.starts_with('-'))
        .cloned()
        .unwrap_or_default();
    let force = args.iter().any(|a| a == "--force" || a == "-f");
    let resource = args.iter().any(|a| a == "--resource" || a == "-r");
    let with_migration = args.iter().any(|a| a == "-m" || a == "--migration");

    if name.is_empty() {
        return Err(crate::error::CliError::InvalidArguments {
            command: kind.command().to_string(),
            detail: "expected a PascalCase name, e.g. make:controller UserController".into(),
        });
    }

    let opts = MakeOptions {
        name,
        force,
        resource,
        with_migration,
    };
    let root = crate::error::project_root(&std::env::current_dir()?)?;
    match generators::generate(kind, &root, &opts) {
        Ok(files) => {
            for file in &files {
                let marker = if file.overwritten {
                    "overwritten"
                } else {
                    "created"
                };
                io.line(format!("{marker}: {}", file.path));
            }
            Ok(())
        }
        Err(err) => Err(err),
    }
}

/// Declare one `make:*` command implementing [`Command`].
macro_rules! make_command {
    ($cmd:ident, $kind:ident, $sig:literal, $help:literal, $usage:literal) => {
        /// Scaffold command generated by the `make_command!` helper.
        pub struct $cmd;

        #[async_trait]
        impl Command for $cmd {
            /// Command signature.
            fn signature(&self) -> &'static str {
                $sig
            }

            /// Usage line rendered by `list`.
            fn usage(&self) -> Option<&'static str> {
                Some($usage)
            }

            /// One-line help rendered by `list`.
            fn help(&self) -> Option<&'static str> {
                Some($help)
            }

            /// Execute the generator.
            async fn run(&self, args: Vec<String>, io: &mut Io) -> CliResult<()> {
                run_make(Kind::$kind, args, io).await
            }
        }
    };
}

make_command!(
    MakeController,
    Controller,
    "make:controller",
    "Make a new controller class",
    "make:controller {name} [--resource] [--force]"
);
make_command!(
    MakeModel,
    Model,
    "make:model",
    "Make a new ORM model",
    "make:model {name} [-m] [--force]"
);
make_command!(
    MakeProvider,
    Provider,
    "make:provider",
    "Make a new service provider",
    "make:provider {name} [--force]"
);
make_command!(
    MakeCommand,
    Command,
    "make:command",
    "Make a new console command",
    "make:command {name} [--force]"
);
make_command!(
    MakeJob,
    Job,
    "make:job",
    "Make a new queue job",
    "make:job {name} [--force]"
);
make_command!(
    MakeEvent,
    Event,
    "make:event",
    "Make a new domain event",
    "make:event {name} [--force]"
);
make_command!(
    MakeListener,
    Listener,
    "make:listener",
    "Make a new event listener",
    "make:listener {name} [--force]"
);
make_command!(
    MakeObserver,
    Observer,
    "make:observer",
    "Make a new model observer",
    "make:observer {name} [--force]"
);
make_command!(
    MakeTest,
    Test,
    "make:test",
    "Make a new feature test",
    "make:test {name} [--force]"
);
make_command!(
    MakeSeeder,
    Seeder,
    "make:seeder",
    "Make a new database seeder",
    "make:seeder {name} [--force]"
);
make_command!(
    MakeAgent,
    Agent,
    "make:agent",
    "Make a new AI agent (M6)",
    "make:agent {name} [--force]"
);
make_command!(
    MakeTool,
    Tool,
    "make:tool",
    "Make a new AI tool (M6)",
    "make:tool {name} [--force]"
);

/// Convenience used by tests to scaffold into a temp root.
pub async fn scaffold_into(
    root: &std::path::Path,
    kind: Kind,
    name: &str,
    force: bool,
) -> CliResult<Vec<Generated>> {
    generators::generate(
        kind,
        root,
        &MakeOptions {
            name: name.to_string(),
            force,
            resource: false,
            with_migration: false,
        },
    )
}
