//! Component registry contract and the generated-registry macro.

use crate::{ClientError, Value};

/// Mounts Inertia components by key.
///
/// Implementations are normally generated by
/// [`inertia_registry!`](crate::inertia_registry) rather than written by hand.
pub trait ComponentRegistry {
    /// Mount `component` with `props`, returning an error when unmapped.
    fn mount(&self, component: &str, props: &Value) -> Result<(), ClientError>;
}

/// Generate a component registry mapping Inertia keys to mount functions.
///
/// WASM has no reflection, so the scaffolder emits this `match` explicitly.
/// Each mount function has the signature `fn(&Value) -> Result<(), ClientError>`.
///
/// ```rust
/// use rustasea_inertia_client::{inertia_registry, ClientError, ComponentRegistry, Value};
///
/// fn mount_login(_props: &Value) -> Result<(), ClientError> {
///     Ok(())
/// }
///
/// inertia_registry!(AppRegistry {
///     "auth/login" => mount_login,
/// });
///
/// fn main() {
///     let registry = AppRegistry::new();
///     assert!(registry.mount("auth/login", &Value::Null).is_ok());
///     assert!(registry.mount("missing", &Value::Null).is_err());
/// }
/// ```
#[macro_export]
macro_rules! inertia_registry {
    ($name:ident { $($key:literal => $mount:path),* $(,)? }) => {
        /// Generated component registry.
        pub struct $name;

        impl $name {
            /// Create the registry.
            pub fn new() -> Self {
                Self
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl $crate::ComponentRegistry for $name {
            fn mount(
                &self,
                component: &str,
                props: &$crate::Value,
            ) -> Result<(), $crate::ClientError> {
                match component {
                    $($key => $mount(props),)*
                    other => Err($crate::ClientError::UnknownComponent {
                        component: other.to_string(),
                    }),
                }
            }
        }
    };
}
